## Add this file to your meteor package as `.travis.yml`

sudo: required
language: node_js
node_js:
  - "0.10"
before_install:
  - "curl https://install.meteor.com/ | sh"
script:
  - "meteor run --test"
