## Add this file to your meteor package as `.travis.yml`

sudo: required
language: node_js
node_js:
  - "0.8"
  - "0.10"
env: TEST_COMMAND=./travis.sh
before_install:
  - "curl https://install.meteor.com/ | sh"
